GRANT ALL PRIVILEGES ON *.* TO 'pq-developer'@'localhost' IDENTIFIED BY 'coluntoda1254';

CREATE DATABASE IF NOT EXISTS EBSCO;
USE EBSCO;

DROP TABLE IF EXISTS USUARIOS;

CREATE TABLE IF NOT EXISTS USUARIOS (
ID INT(11) NOT NULL AUTO_INCREMENT,
PRIMER_NOMBRE VARCHAR(100) DEFAULT NULL,
SEGUNDO_NOMBRE VARCHAR(100) DEFAULT NULL,
PRIMER_APELLIDO VARCHAR(100) DEFAULT NULL,
SEGUNDO_APELLIDO VARCHAR(100) DEFAULT NULL,
BIRTHDAY DATE NOT NULL,
EMAIL VARCHAR(100) DEFAULT NULL,
PASSWORD VARCHAR(100),
PRIMARY KEY(ID)
);

DELETE FROM USUARIOS;

INSERT INTO USUARIOS(PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,BIRTHDAY,EMAIL,PASSWORD) 
VALUES('Cristian','Alejandro','Taruman','Betancourt','1996-09-06','cris.taruman@gmail.com','coluntoda1254'),
('Maria','Jose','Quezada','Quezada','1988-01-09','maria.quezada@gmail.com','coluntoda1254'),
('Alfonso','Henriquez','Taruman','Avendaño','1960-01-10','alfonso.taruman@gmail.com','coluntoda1254');

COMMIT;